import 'package:flutter/material.dart';
import 'package:flutter_image/flutter_image.dart';
import 'package:world_clock/services/world_time.dart';

class ChooseLocation extends StatefulWidget {
  const ChooseLocation({Key? key}) : super(key: key);

  @override
  State<ChooseLocation> createState() => _ChooseLocationState();
}

class _ChooseLocationState extends State<ChooseLocation> {
  
  List<WorldTime> locations = [
    WorldTime(location: "Kabul, Afghanistan", flag: "AF", utc: "+04:30"),
    WorldTime(location: "Mariehamn, Aland Islands", flag: "AX", utc: "+02:00"),
    WorldTime(location: "Tirane, Albania", flag: "AL", utc: "+01:00"),
    WorldTime(location: "Algiers, Algeria", flag: "DZ", utc: "+01:00"),
    WorldTime(location: "Pago Pago, American Samoa", flag: "AS", utc: "-11:00"),
    WorldTime(location: "Andorra, Andorra", flag: "AD", utc: "+01:00"),
    WorldTime(location: "Buenos Aires, Argentina", flag: "AR", utc: "-03:00"),
    WorldTime(location: "Catamarca, Argentina", flag: "AR", utc: "-03:00"),
    WorldTime(location: "Cordoba, Argentina", flag: "AR", utc: "-03:00"),
    WorldTime(location: "Jujuy, Argentina", flag: "AR", utc: "-03:00"),
    WorldTime(location: "La Rioja, Argentina", flag: "AR", utc: "-03:00"),
    WorldTime(location: "Mendoza, Argentina", flag: "AR", utc: "-03:00"),
    WorldTime(location: "Rio Gallegos, Argentina", flag: "AR", utc: "-03:00"),
    WorldTime(location: "Salta, Argentina", flag: "AR", utc: "-03:00"),
    WorldTime(location: "San Juan, Argentina", flag: "AR", utc: "-03:00"),
    WorldTime(location: "San Luis, Argentina", flag: "AR", utc: "-03:00"),
    WorldTime(location: "Tucuman, Argentina", flag: "AR", utc: "-03:00"),
    WorldTime(location: "Ushuaia, Argentina", flag: "AR", utc: "-03:00"),
    WorldTime(location: "Rothera, Argentina", flag: "AR", utc: "-03:00"),
    WorldTime(location: "Yerevan, Armenia", flag: "AM", utc: "+04:00"),
    WorldTime(location: "Casey, Australia", flag: "AU", utc: "+11:00"),
    WorldTime(location: "Davis, Australia", flag: "AU", utc: "+07:00"),
    WorldTime(location: "Macquarie, Australia", flag: "AU", utc: "+11:00"),
    WorldTime(location: "Mawson, Australia", flag: "AU", utc: "+05:00"),
    WorldTime(location: "Adelaide, Australia", flag: "AU", utc: "+10:30"),
    WorldTime(location: "Brisbane, Australia", flag: "AU", utc: "+10:00"),
    WorldTime(location: "Broken Hill, Australia", flag: "AU", utc: "+10:30"),
    WorldTime(location: "Darwin, Australia", flag: "AU", utc: "+09:30"),
    WorldTime(location: "Eucla, Australia", flag: "AU", utc: "+08:45"),
    WorldTime(location: "Hobart, Australia", flag: "AU", utc: "+11:00"),
    WorldTime(location: "Lindeman, Australia", flag: "AU", utc: "+10:00"),
    WorldTime(location: "Lord Howe, Australia", flag: "AU", utc: "+11:00"),
    WorldTime(location: "Melbourne, Australia", flag: "AU", utc: "+11:00"),
    WorldTime(location: "Perth, Australia", flag: "AU", utc: "+08:00"),
    WorldTime(location: "Sydney, Australia", flag: "AU", utc: "+11:00"),
    WorldTime(location: "Vienna, Austria", flag: "AT", utc: "+01:00"),
    WorldTime(location: "Baku, Azerbaijan", flag: "AZ", utc: "+04:00"),
    WorldTime(location: "Nassau, Bahamas", flag: "BS", utc: "-05:00"),
    WorldTime(location: "Guernsey, Bailiwick of Guernsey", flag: "GG", utc: "+00:00"),
    WorldTime(location: "Jersey, Bailiwick of Jersey", flag: "JE", utc: "+00:00"),
    WorldTime(location: "Dhaka, Bangladesh", flag: "BD", utc: "+06:00"),
    WorldTime(location: "Barbados, Barbados", flag: "BB", utc: "-04:00"),
    WorldTime(location: "Minsk, Belarus", flag: "BY", utc: "+03:00"),
    WorldTime(location: "Brussels, Belgium", flag: "BE", utc: "+01:00"),
    WorldTime(location: "Belize, Belize", flag: "BZ", utc: "-06:00"),
    WorldTime(location: "Bermuda, Bermuda", flag: "BM", utc: "-04:00"),
    WorldTime(location: "Thimphu, Bhutan", flag: "BT", utc: "+06:00"),
    WorldTime(location: "La Paz, Bolivia", flag: "BO", utc: "-04:00"),
    WorldTime(location: "Sarajevo, Bosnia and Herzegovina", flag: "BA", utc: "+01:00"),
    WorldTime(location: "Araguaina, Brazil", flag: "BR", utc: "-03:00"),
    WorldTime(location: "Bahia, Brazil", flag: "BR", utc: "-03:00"),
    WorldTime(location: "Belem, Brazil", flag: "BR", utc: "-03:00"),
    WorldTime(location: "Boa Vista, Brazil", flag: "BR", utc: "-04:00"),
    WorldTime(location: "Campo Grande, Brazil", flag: "BR", utc: "-04:00"),
    WorldTime(location: "Cuiaba, Brazil", flag: "BR", utc: "-04:00"),
    WorldTime(location: "Eirunepe, Brazil", flag: "BR", utc: "-05:00"),
    WorldTime(location: "Fortaleza, Brazil", flag: "BR", utc: "-03:00"),
    WorldTime(location: "Maceio, Brazil", flag: "BR", utc: "-03:00"),
    WorldTime(location: "Manaus, Brazil", flag: "BR", utc: "-04:00"),
    WorldTime(location: "Noronha, Brazil", flag: "BR", utc: "-02:00"),
    WorldTime(location: "Porto Velho, Brazil", flag: "BR", utc: "-04:00"),
    WorldTime(location: "Recife, Brazil", flag: "BR", utc: "-03:00"),
    WorldTime(location: "Rio Branco, Brazil", flag: "BR", utc: "-05:00"),
    WorldTime(location: "Santarem, Brazil", flag: "BR", utc: "-03:00"),
    WorldTime(location: "Sao Paulo, Brazil", flag: "BR", utc: "-03:00"),
    WorldTime(location: "Chagos, British Indian Ocean Territory", flag: "IO", utc: "+06:00"),
    WorldTime(location: "South Georgia, British Overseas Territory", flag: "VG", utc: "-02:00"),
    WorldTime(location: "Brunei, Brunei", flag: "BN", utc: "+08:00"),
    WorldTime(location: "Sofia, Bulgaria", flag: "BG", utc: "+02:00"),
    WorldTime(location: "Phnom Penh, Cambodia", flag: "KH", utc: "+07:00"),
    WorldTime(location: "Atikokan, Canada", flag: "CA", utc: "-05:00"),
    WorldTime(location: "Blanc-Sablon, Canada", flag: "CA", utc: "-04:00"),
    WorldTime(location: "Cambridge Bay, Canada", flag: "CA", utc: "-07:00"),
    WorldTime(location: "Creston, Canada", flag: "CA", utc: "-07:00"),
    WorldTime(location: "Dawson, Canada", flag: "CA", utc: "-07:00"),
    WorldTime(location: "Dawson Creek, Canada", flag: "CA", utc: "-07:00"),
    WorldTime(location: "Edmonton, Canada", flag: "CA", utc: "-07:00"),
    WorldTime(location: "Fort Nelson, Canada", flag: "CA", utc: "-07:00"),
    WorldTime(location: "Glace Bay, Canada", flag: "CA", utc: "-04:00"),
    WorldTime(location: "Goose Bay, Canada", flag: "CA", utc: "-04:00"),
    WorldTime(location: "Halifax, Canada", flag: "CA", utc: "-04:00"),
    WorldTime(location: "Inuvik, Canada", flag: "CA", utc: "-07:00"),
    WorldTime(location: "Iqaluit, Canada", flag: "CA", utc: "-05:00"),
    WorldTime(location: "Moncton, Canada", flag: "CA", utc: "-04:00"),
    WorldTime(location: "Nipigon, Canada", flag: "CA", utc: "-05:00"),
    WorldTime(location: "Pangnirtung, Canada", flag: "CA", utc: "-05:00"),
    WorldTime(location: "Rainy River, Canada", flag: "CA", utc: "-06:00"),
    WorldTime(location: "Rankin Inlet, Canada", flag: "CA", utc: "-06:00"),
    WorldTime(location: "Regina, Canada", flag: "CA", utc: "-06:00"),
    WorldTime(location: "Resolute, Canada", flag: "CA", utc: "-06:00"),
    WorldTime(location: "St Johns, Canada", flag: "CA", utc: "-03:30"),
    WorldTime(location: "Swift Current, Canada", flag: "CA", utc: "-06:00"),
    WorldTime(location: "Thunder Bay, Canada", flag: "CA", utc: "-05:00"),
    WorldTime(location: "Toronto, Canada", flag: "CA", utc: "-05:00"),
    WorldTime(location: "Vancouver, Canada", flag: "CA", utc: "-08:00"),
    WorldTime(location: "Whitehorse, Canada", flag: "CA", utc: "-07:00"),
    WorldTime(location: "Winnipeg, Canada", flag: "CA", utc: "-06:00"),
    WorldTime(location: "Yellowknife, Canada", flag: "CA", utc: "-07:00"),
    WorldTime(location: "Cape Verde, Cape Verde", flag: "CV", utc: "-01:00"),
    WorldTime(location: "Ndjamena, Chad", flag: "TD", utc: "+01:00"),
    WorldTime(location: "Punta Arenas, Chile", flag: "CL", utc: "-03:00"),
    WorldTime(location: "Santiago, Chile", flag: "CL", utc: "-03:00"),
    WorldTime(location: "Palmer, Chile", flag: "CL", utc: "-03:00"),
    WorldTime(location: "Easter, Chile", flag: "CL", utc: "-05:00"),
    WorldTime(location: "Macau, China", flag: "CN", utc: "+08:00"),
    WorldTime(location: "Shanghai, China", flag: "CN", utc: "+08:00"),
    WorldTime(location: "Urumqi, China", flag: "CN", utc: "+06:00"),
    WorldTime(location: "Christmas, Christmas Island", flag: "CX", utc: "+07:00"),
    WorldTime(location: "Kiritimati, Christmas Island", flag: "CX", utc: "+14:00"),
    WorldTime(location: "Cocos, Cocos Islands", flag: "CC", utc: "+06:30"),
    WorldTime(location: "Bogota, Colombia", flag: "CO", utc: "-05:00"),
    WorldTime(location: "Comoro, Comoros", flag: "KM", utc: "+03:00"),
    WorldTime(location: "Rarotonga, Cook Islands", flag: "CK", utc: "-10:00"),
    WorldTime(location: "Costa Rica, Costa Rica", flag: "CR", utc: "-06:00"),
    WorldTime(location: "Zagreb, Croatia", flag: "HR", utc: "+01:00"),
    WorldTime(location: "Havana, Cuba", flag: "CU", utc: "-05:00"),
    WorldTime(location: "Famagusta, Cyprus", flag: "CY", utc: "+02:00"),
    WorldTime(location: "Nicosia, Cyprus", flag: "CY", utc: "+02:00"),
    WorldTime(location: "Prague, Czech Republic", flag: "CZ", utc: "+01:00"),
    WorldTime(location: "Copenhagen, Denmark", flag: "DK", utc: "+01:00"),
    WorldTime(location: "Santo Domingo, Dominican Republic", flag: "DO", utc: "-04:00"),
    WorldTime(location: "Guayaquil, Ecuador", flag: "EC", utc: "-05:00"),
    WorldTime(location: "Cairo, Egypt", flag: "EG", utc: "+02:00"),
    WorldTime(location: "El Salvador, El Salvador", flag: "SV", utc: "-06:00"),
    WorldTime(location: "Tallinn, Estonia", flag: "EE", utc: "+02:00"),
    WorldTime(location: "Stanley, Falkland Islands", flag: "FK", utc: "-03:00"),
    WorldTime(location: "Faroe, Faroe Islands", flag: "FO", utc: "+00:00"),
    WorldTime(location: "Fiji, Fiji", flag: "FJ", utc: "+12:00"),
    WorldTime(location: "Helsinki, Finland", flag: "FI", utc: "+02:00"),
    WorldTime(location: "Cayenne, France", flag: "FR", utc: "-03:00"),
    WorldTime(location: "Martinique, France", flag: "FR", utc: "-04:00"),
    WorldTime(location: "Miquelon, France", flag: "FR", utc: "-03:00"),
    WorldTime(location: "DumontDUrville, France", flag: "FR", utc: "+10:00"),
    WorldTime(location: "Paris, France", flag: "FR", utc: "+01:00"),
    WorldTime(location: "Gambier, French Polynesia", flag: "PF", utc: "-09:00"),
    WorldTime(location: "Marquesas, French Polynesia", flag: "PF", utc: "-09:30"),
    WorldTime(location: "Tahiti, French Polynesia", flag: "PF", utc: "-10:00"),
    WorldTime(location: "Kerguelen, French Southern and Antarctic Lands", flag: "TF", utc: "+05:00"),
    WorldTime(location: "Galapagos, Galápagos Islands", flag: "EC", utc: "-06:00"),
    WorldTime(location: "Tbilisi, Georgia", flag: "GE", utc: "+04:00"),
    WorldTime(location: "Berlin, Germany", flag: "DE", utc: "+01:00"),
    WorldTime(location: "Busingen, Germany", flag: "DE", utc: "+01:00"),
    WorldTime(location: "Accra, Ghana", flag: "GH", utc: "+00:00"),
    WorldTime(location: "Gibraltar, Gibraltar", flag: "GI", utc: "+01:00"),
    WorldTime(location: "Athens, Greece", flag: "GR", utc: "+02:00"),
    WorldTime(location: "Danmarkshavn, Greenland", flag: "GL", utc: "+00:00"),
    WorldTime(location: "Nuuk, Greenland", flag: "GL", utc: "-03:00"),
    WorldTime(location: "Scoresbysund, Greenland", flag: "GL", utc: "-01:00"),
    WorldTime(location: "Thule, Greenland", flag: "GL", utc: "-04:00"),
    WorldTime(location: "Guam, Guam", flag: "GU", utc: "+10:00"),
    WorldTime(location: "Guatemala, Guatemala", flag: "GT", utc: "-06:00"),
    WorldTime(location: "Bissau, Guinea-Bissau", flag: "GW", utc: "+00:00"),
    WorldTime(location: "Guyana, Guyana", flag: "GY", utc: "-04:00"),
    WorldTime(location: "Port-au-Prince, Haiti", flag: "HT", utc: "-05:00"),
    WorldTime(location: "Tegucigalpa, Honduras", flag: "HN", utc: "-06:00"),
    WorldTime(location: "Hong Kong, Hong Kong", flag: "HK", utc: "+08:00"),
    WorldTime(location: "Budapest, Hungary", flag: "HU", utc: "+01:00"),
    WorldTime(location: "Reykjavik, Iceland", flag: "IS", utc: "+00:00"),
    WorldTime(location: "Kolkata, India", flag: "IN", utc: "+05:30"),
    WorldTime(location: "Jakarta, Indonesia", flag: "ID", utc: "+07:00"),
    WorldTime(location: "Jayapura, Indonesia", flag: "ID", utc: "+09:00"),
    WorldTime(location: "Makassar, Indonesia", flag: "ID", utc: "+08:00"),
    WorldTime(location: "Pontianak, Indonesia", flag: "ID", utc: "+07:00"),
    WorldTime(location: "Tehran, Iran", flag: "IR", utc: "+03:30"),
    WorldTime(location: "Baghdad, Iraq", flag: "IQ", utc: "+03:00"),
    WorldTime(location: "Dublin, Ireland", flag: "IE", utc: "+00:00"),
    WorldTime(location: "Isle of Man, Isle of Man", flag: "IM", utc: "+00:00"),
    WorldTime(location: "Jerusalem, Israel", flag: "IL", utc: "+02:00"),
    WorldTime(location: "Rome, Italy", flag: "IT", utc: "+01:00"),
    WorldTime(location: "Abidjan, Ivory Coast", flag: "CI", utc: "+00:00"),
    WorldTime(location: "Jamaica, Jamaica", flag: "JM", utc: "-05:00"),
    WorldTime(location: "Syowa, Japan", flag: "JP", utc: "+03:00"),
    WorldTime(location: "Tokyo, Japan", flag: "JP", utc: "+09:00"),
    WorldTime(location: "Amman, Jordan", flag: "JO", utc: "+02:00"),
    WorldTime(location: "Almaty, Kazakhstan", flag: "KZ", utc: "+06:00"),
    WorldTime(location: "Aqtau, Kazakhstan", flag: "KZ", utc: "+05:00"),
    WorldTime(location: "Aqtobe, Kazakhstan", flag: "KZ", utc: "+05:00"),
    WorldTime(location: "Atyrau, Kazakhstan", flag: "KZ", utc: "+05:00"),
    WorldTime(location: "Oral, Kazakhstan", flag: "KZ", utc: "+05:00"),
    WorldTime(location: "Qyzylorda, Kazakhstan", flag: "KZ", utc: "+05:00"),
    WorldTime(location: "Nairobi, Kenya", flag: "KE", utc: "+03:00"),
    WorldTime(location: "Enderbury, Kiribati", flag: "KI", utc: "+13:00"),
    WorldTime(location: "Tarawa, Kiribati", flag: "KI", utc: "+12:00"),
    WorldTime(location: "Bishkek, Kyrgyzstan", flag: "KG", utc: "+06:00"),
    WorldTime(location: "Vientiane, Laos", flag: "LA", utc: "+07:00"),
    WorldTime(location: "Riga, Latvia", flag: "LV", utc: "+02:00"),
    WorldTime(location: "Beirut, Lebanon", flag: "LB", utc: "+02:00"),
    WorldTime(location: "Monrovia, Liberia", flag: "LR", utc: "+00:00"),
    WorldTime(location: "Tripoli, Libya", flag: "LY", utc: "+02:00"),
    WorldTime(location: "Vaduz, Liechtenstein", flag: "LI", utc: "+01:00"),
    WorldTime(location: "Vilnius, Lithuania", flag: "LT", utc: "+02:00"),
    WorldTime(location: "Luxembourg, Luxembourg", flag: "LU", utc: "+01:00"),
    WorldTime(location: "Antananarivo, Madagascar", flag: "MG", utc: "+03:00"),
    WorldTime(location: "Kuala Lumpur, Malaysia", flag: "MY", utc: "+08:00"),
    WorldTime(location: "Kuching, Malaysia", flag: "MY", utc: "+08:00"),
    WorldTime(location: "Maldives, Maldives", flag: "MV", utc: "+05:00"),
    WorldTime(location: "Malta, Malta", flag: "MT", utc: "+01:00"),
    WorldTime(location: "Kwajalein, Marshall Islands", flag: "MH", utc: "+12:00"),
    WorldTime(location: "Majuro, Marshall Islands", flag: "MH", utc: "+12:00"),
    WorldTime(location: "Mauritius, Mauritius", flag: "MU", utc: "+04:00"),
    WorldTime(location: "Mayotte, Mayotte", flag: "YT", utc: "+03:00"),
    WorldTime(location: "Bahia Banderas, Mexico", flag: "MX", utc: "-06:00"),
    WorldTime(location: "Cancun, Mexico", flag: "MX", utc: "-05:00"),
    WorldTime(location: "Chihuahua, Mexico", flag: "MX", utc: "-07:00"),
    WorldTime(location: "Hermosillo, Mexico", flag: "MX", utc: "-07:00"),
    WorldTime(location: "Matamoros, Mexico", flag: "MX", utc: "-06:00"),
    WorldTime(location: "Mazatlan, Mexico", flag: "MX", utc: "-07:00"),
    WorldTime(location: "Merida, Mexico", flag: "MX", utc: "-06:00"),
    WorldTime(location: "Mexico City, Mexico", flag: "MX", utc: "-06:00"),
    WorldTime(location: "Monterrey, Mexico", flag: "MX", utc: "-06:00"),
    WorldTime(location: "Ojinaga, Mexico", flag: "MX", utc: "-07:00"),
    WorldTime(location: "Tijuana, Mexico", flag: "MX", utc: "-08:00"),
    WorldTime(location: "Chuuk, Micronesia", flag: "FM", utc: "+10:00"),
    WorldTime(location: "Kosrae, Micronesia", flag: "FM", utc: "+11:00"),
    WorldTime(location: "Pohnpei, Micronesia", flag: "FM", utc: "+11:00"),
    WorldTime(location: "Chisinau, Moldova", flag: "MD", utc: "+02:00"),
    WorldTime(location: "Monaco, Monaco", flag: "MC", utc: "+01:00"),
    WorldTime(location: "Choibalsan, Mongolia", flag: "MN", utc: "+08:00"),
    WorldTime(location: "Hovd, Mongolia", flag: "MN", utc: "+07:00"),
    WorldTime(location: "Ulaanbaatar, Mongolia", flag: "MN", utc: "+08:00"),
    WorldTime(location: "Podgorica, Montenegro", flag: "ME", utc: "+01:00"),
    WorldTime(location: "Casablanca, Morocco", flag: "MA", utc: "+01:00"),
    WorldTime(location: "Maputo, Mozambique", flag: "MZ", utc: "+02:00"),
    WorldTime(location: "Windhoek, Namibia", flag: "NA", utc: "+02:00"),
    WorldTime(location: "Nauru, Nauru", flag: "NR", utc: "+12:00"),
    WorldTime(location: "Kathmandu, Nepal", flag: "NP", utc: "+05:45"),
    WorldTime(location: "Curacao, Netherlands", flag: "NL", utc: "-04:00"),
    WorldTime(location: "Amsterdam, Netherlands", flag: "NL", utc: "+01:00"),
    WorldTime(location: "Noumea, New Caledonia", flag: "NC", utc: "+11:00"),
    WorldTime(location: "Auckland, New Zealand", flag: "NZ", utc: "+13:00"),
    WorldTime(location: "Chatham, New Zealand", flag: "NZ", utc: "+13:45"),
    WorldTime(location: "Managua, Nicaragua", flag: "NI", utc: "-06:00"),
    WorldTime(location: "Lagos, Nigeria", flag: "NG", utc: "+01:00"),
    WorldTime(location: "Niue, Niue", flag: "NU", utc: "-11:00"),
    WorldTime(location: "Norfolk, Norfolk Island", flag: "NF", utc: "+12:00"),
    WorldTime(location: "Pyongyang, North Korea", flag: "KP", utc: "+09:00"),
    WorldTime(location: "Skopje, North Macedonia", flag: "MK", utc: "+01:00"),
    WorldTime(location: "Saipan, Northern Mariana Islands", flag: "MP", utc: "+10:00"),
    WorldTime(location: "Troll, Norway", flag: "NO", utc: "+00:00"),
    WorldTime(location: "Oslo, Norway", flag: "NO", utc: "+01:00"),
    WorldTime(location: "Karachi, Pakistan", flag: "PK", utc: "+05:00"),
    WorldTime(location: "Palau, Palau", flag: "PW", utc: "+09:00"),
    WorldTime(location: "Gaza, Palestine", flag: "PS", utc: "+02:00"),
    WorldTime(location: "Hebron, Palestine", flag: "PS", utc: "+02:00"),
    WorldTime(location: "Panama, Panama", flag: "PA", utc: "-05:00"),
    WorldTime(location: "Bougainville, Papua New Guinea", flag: "PG", utc: "+11:00"),
    WorldTime(location: "Port Moresby, Papua New Guinea", flag: "PG", utc: "+10:00"),
    WorldTime(location: "Asuncion, Paraguay", flag: "PY", utc: "-03:00"),
    WorldTime(location: "Lima, Peru", flag: "PE", utc: "-05:00"),
    WorldTime(location: "Manila, Philippines", flag: "PH", utc: "+08:00"),
    WorldTime(location: "Pitcairn, Pitcairn Islands", flag: "PN", utc: "-08:00"),
    WorldTime(location: "Warsaw, Poland", flag: "PL", utc: "+01:00"),
    WorldTime(location: "Azores, Portugal", flag: "PT", utc: "-01:00"),
    WorldTime(location: "Madeira, Portugal", flag: "PT", utc: "+00:00"),
    WorldTime(location: "Lisbon, Portugal", flag: "PT", utc: "+00:00"),
    WorldTime(location: "Puerto Rico, Puerto Rico", flag: "PR", utc: "-04:00"),
    WorldTime(location: "Qatar, Qatar", flag: "QA", utc: "+03:00"),
    WorldTime(location: "Reunion, Reunion", flag: "RE", utc: "+04:00"),
    WorldTime(location: "Bucharest, Romania", flag: "RO", utc: "+02:00"),
    WorldTime(location: "Vostok, Russia", flag: "RU", utc: "+06:00"),
    WorldTime(location: "Anadyr, Russia", flag: "RU", utc: "+12:00"),
    WorldTime(location: "Barnaul, Russia", flag: "RU", utc: "+07:00"),
    WorldTime(location: "Chita, Russia", flag: "RU", utc: "+09:00"),
    WorldTime(location: "Irkutsk, Russia", flag: "RU", utc: "+08:00"),
    WorldTime(location: "Kamchatka, Russia", flag: "RU", utc: "+12:00"),
    WorldTime(location: "Khandyga, Russia", flag: "RU", utc: "+09:00"),
    WorldTime(location: "Krasnoyarsk, Russia", flag: "RU", utc: "+07:00"),
    WorldTime(location: "Magadan, Russia", flag: "RU", utc: "+11:00"),
    WorldTime(location: "Novokuznetsk, Russia", flag: "RU", utc: "+07:00"),
    WorldTime(location: "Novosibirsk, Russia", flag: "RU", utc: "+07:00"),
    WorldTime(location: "Omsk, Russia", flag: "RU", utc: "+06:00"),
    WorldTime(location: "Sakhalin, Russia", flag: "RU", utc: "+11:00"),
    WorldTime(location: "Srednekolymsk, Russia", flag: "RU", utc: "+11:00"),
    WorldTime(location: "Tomsk, Russia", flag: "RU", utc: "+07:00"),
    WorldTime(location: "Vladivostok, Russia", flag: "RU", utc: "+10:00"),
    WorldTime(location: "Yakutsk, Russia", flag: "RU", utc: "+09:00"),
    WorldTime(location: "Yekaterinburg, Russia", flag: "RU", utc: "+05:00"),
    WorldTime(location: "Astrakhan, Russia", flag: "RU", utc: "+04:00"),
    WorldTime(location: "Kaliningrad, Russia", flag: "RU", utc: "+02:00"),
    WorldTime(location: "Kirov, Russia", flag: "RU", utc: "+03:00"),
    WorldTime(location: "Moscow, Russia", flag: "RU", utc: "+03:00"),
    WorldTime(location: "Samara, Russia", flag: "RU", utc: "+04:00"),
    WorldTime(location: "Simferopol, Russia", flag: "RU", utc: "+03:00"),
    WorldTime(location: "Ulyanovsk, Russia", flag: "RU", utc: "+04:00"),
    WorldTime(location: "Volgograd, Russia", flag: "RU", utc: "+03:00"),
    WorldTime(location: "St Helena, Saint Helena, Ascension and Tristan da Cunha", flag: "SH", utc: "+00:00"),
    WorldTime(location: "Apia, Samoa", flag: "WS", utc: "+14:00"),
    WorldTime(location: "San Marino, San Marino", flag: "SM", utc: "+01:00"),
    WorldTime(location: "Sao Tome, Sao Tome and Principe", flag: "ST", utc: "+00:00"),
    WorldTime(location: "Riyadh, Saudi Arabia", flag: "SA", utc: "+03:00"),
    WorldTime(location: "Belgrade, Serbia", flag: "RS", utc: "+01:00"),
    WorldTime(location: "Mahe, Seychelles", flag: "SC", utc: "+04:00"),
    WorldTime(location: "Singapore, Singapore", flag: "SG", utc: "+08:00"),
    WorldTime(location: "Bratislava, Slovakia", flag: "SK", utc: "+01:00"),
    WorldTime(location: "Ljubljana, Slovenia", flag: "SI", utc: "+01:00"),
    WorldTime(location: "Guadalcanal, Solomon Islands", flag: "SB", utc: "+11:00"),
    WorldTime(location: "Johannesburg, South Africa", flag: "ZA", utc: "+02:00"),
    WorldTime(location: "Seoul, South Korea", flag: "KR", utc: "+09:00"),
    WorldTime(location: "Juba, South Sudan", flag: "SS", utc: "+02:00"),
    WorldTime(location: "Ceuta, Spain", flag: "ES", utc: "+01:00"),
    WorldTime(location: "Canary, Spain", flag: "ES", utc: "+00:00"),
    WorldTime(location: "Madrid, Spain", flag: "ES", utc: "+01:00"),
    WorldTime(location: "Colombo, Sri Lanka", flag: "LK", utc: "+05:30"),
    WorldTime(location: "Khartoum, Sudan", flag: "SD", utc: "+02:00"),
    WorldTime(location: "Paramaribo, Suriname", flag: "SR", utc: "-03:00"),
    WorldTime(location: "Stockholm, Sweden", flag: "SE", utc: "+01:00"),
    WorldTime(location: "Zurich, Switzerland", flag: "CH", utc: "+01:00"),
    WorldTime(location: "Damascus, Syria", flag: "SY", utc: "+02:00"),
    WorldTime(location: "Taipei, Taiwan", flag: "TW", utc: "+08:00"),
    WorldTime(location: "Dushanbe, Tajikistan", flag: "TJ", utc: "+05:00"),
    WorldTime(location: "Bangkok, Thailand", flag: "TH", utc: "+07:00"),
    WorldTime(location: "Dili, Timor-Leste", flag: "TL", utc: "+09:00"),
    WorldTime(location: "Fakaofo, Tokelau", flag: "TK", utc: "+13:00"),
    WorldTime(location: "Tongatapu, Tonga", flag: "TO", utc: "+13:00"),
    WorldTime(location: "Port of Spain, Trinidad and Tobago", flag: "TT", utc: "-04:00"),
    WorldTime(location: "Tunis, Tunisia", flag: "TN", utc: "+01:00"),
    WorldTime(location: "Istanbul, Turkey", flag: "TR", utc: "+03:00"),
    WorldTime(location: "Ashgabat, Turkmenistan", flag: "TM", utc: "+05:00"),
    WorldTime(location: "Grand Turk, Turks and Caicos Islands", flag: "TC", utc: "-05:00"),
    WorldTime(location: "Funafuti, Tuvalu", flag: "TV", utc: "+12:00"),
    WorldTime(location: "Kiev, Ukraine", flag: "UA", utc: "+02:00"),
    WorldTime(location: "Uzhgorod, Ukraine", flag: "UA", utc: "+02:00"),
    WorldTime(location: "Zaporozhye, Ukraine", flag: "UA", utc: "+02:00"),
    WorldTime(location: "Dubai, United Arab Emirates", flag: "AE", utc: "+04:00"),
    WorldTime(location: "London, United Kingdom", flag: "GB", utc: "+00:00"),
    WorldTime(location: "Adak, United States", flag: "US", utc: "-10:00"),
    WorldTime(location: "Anchorage, United States", flag: "US", utc: "-09:00"),
    WorldTime(location: "Boise, United States", flag: "US", utc: "-07:00"),
    WorldTime(location: "Chicago, United States", flag: "US", utc: "-06:00"),
    WorldTime(location: "Denver, United States", flag: "US", utc: "-07:00"),
    WorldTime(location: "Detroit, United States", flag: "US", utc: "-05:00"),
    WorldTime(location: "Indianapolis, United States", flag: "US", utc: "-05:00"),
    WorldTime(location: "Knox, United States", flag: "US", utc: "-06:00"),
    WorldTime(location: "Marengo, United States", flag: "US", utc: "-05:00"),
    WorldTime(location: "Petersburg, United States", flag: "US", utc: "-05:00"),
    WorldTime(location: "Tell City, United States", flag: "US", utc: "-06:00"),
    WorldTime(location: "Vevay, United States", flag: "US", utc: "-05:00"),
    WorldTime(location: "Vincennes, United States", flag: "US", utc: "-05:00"),
    WorldTime(location: "Winamac, United States", flag: "US", utc: "-05:00"),
    WorldTime(location: "Juneau, United States", flag: "US", utc: "-09:00"),
    WorldTime(location: "Louisville, United States", flag: "US", utc: "-05:00"),
    WorldTime(location: "Monticello, United States", flag: "US", utc: "-05:00"),
    WorldTime(location: "Los Angeles, United States", flag: "US", utc: "-08:00"),
    WorldTime(location: "Menominee, United States", flag: "US", utc: "-06:00"),
    WorldTime(location: "Metlakatla, United States", flag: "US", utc: "-09:00"),
    WorldTime(location: "New York, United States", flag: "US", utc: "-05:00"),
    WorldTime(location: "Nome, United States", flag: "US", utc: "-09:00"),
    WorldTime(location: "Beulah, United States", flag: "US", utc: "-06:00"),
    WorldTime(location: "Center, United States", flag: "US", utc: "-06:00"),
    WorldTime(location: "New Salem, United States", flag: "US", utc: "-06:00"),
    WorldTime(location: "Phoenix, United States", flag: "US", utc: "-07:00"),
    WorldTime(location: "Sitka, United States", flag: "US", utc: "-09:00"),
    WorldTime(location: "Yakutat, United States", flag: "US", utc: "-09:00"),
    WorldTime(location: "Honolulu, United States", flag: "US", utc: "-10:00"),
    WorldTime(location: "Midway, United States", flag: "US", utc: "-11:00"),
    WorldTime(location: "Wake, United States", flag: "US", utc: "+12:00"),
    WorldTime(location: "Montevideo, Uruguay", flag: "UY", utc: "-03:00"),
    WorldTime(location: "Samarkand, Uzbekistan", flag: "UZ", utc: "+05:00"),
    WorldTime(location: "Tashkent, Uzbekistan", flag: "UZ", utc: "+05:00"),
    WorldTime(location: "Efate, Vanuatu", flag: "VU", utc: "+11:00"),
    WorldTime(location: "Vatican, Vatican City", flag: "VA", utc: "+01:00"),
    WorldTime(location: "Caracas, Venezuela", flag: "VE", utc: "-04:00"),
    WorldTime(location: "Ho Chi Minh, Vietnam", flag: "VN", utc: "+07:00"),
    WorldTime(location: "Wallis, Wallis and Futuna", flag: "WF", utc: "+12:00"),
    WorldTime(location: "El Aaiun, Western Sahara", flag: "EH", utc: "+01:00"),
  ];

  late NavigatorState navigator = NavigatorState();

  void updateTime(index) async {
    WorldTime instance = locations[index];
    navigator.pop({
      'location': instance.location,
      'flag': "https://countryflagsapi.com/png/${instance.flag}",
      'time': instance.time,
      'isDayTime': instance.isDayTime
    });
  }

  @override
  void initState() {
    super.initState();
    navigator = Navigator.of(context);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey[100],
      appBar: AppBar(
        backgroundColor: Colors.blue.shade900,
        title: const Text("Choose a location"),
        centerTitle: true,
        elevation: 0,
      ),
      body: ListView.builder(
        itemCount: locations.length,
        itemBuilder: (context, index) {
          return Padding(
            padding: const EdgeInsets.symmetric(vertical: 1, horizontal: 4),
            child: Card(
              child: ListTile(
                leading: CircleAvatar(
                  radius: 25,
                  backgroundImage: NetworkImageWithRetry(
                      "https://countryflagsapi.com/png/${locations[index].flag}"
                  ),
                ),
                onTap: () {
                  updateTime(index);
                },
                title: Text(locations[index].location),
              ),
            ),
          );
        },
      ),
    );
  }
}
