import requests

timezone_to_country = {
    'Africa/Abidjan': 'Ivory Coast',
    'Africa/Accra': 'Ghana',
    'Africa/Algiers': 'Algeria',
    'Africa/Bissau': 'Guinea-Bissau',
    'Africa/Cairo': 'Egypt',
    'Africa/Casablanca': 'Morocco',
    'Africa/Ceuta': 'Spain',
    'Africa/El_Aaiun': 'Western Sahara',
    'Africa/Johannesburg': 'South Africa',
    'Africa/Juba': 'South Sudan',
    'Africa/Khartoum': 'Sudan',
    'Africa/Lagos': 'Nigeria',
    'Africa/Maputo': 'Mozambique',
    'Africa/Monrovia': 'Liberia',
    'Africa/Nairobi': 'Kenya',
    'Africa/Ndjamena': 'Chad',
    'Africa/Sao_Tome': 'Sao Tome and Principe',
    'Africa/Tripoli': 'Libya',
    'Africa/Tunis': 'Tunisia',
    'Africa/Windhoek': 'Namibia',
    'America/Adak': 'United States',
    'America/Anchorage': 'United States',
    'America/Araguaina': 'Brazil',
    'America/Argentina/Buenos_Aires': 'Argentina',
    'America/Argentina/Catamarca': 'Argentina',
    'America/Argentina/Cordoba': 'Argentina',
    'America/Argentina/Jujuy': 'Argentina',
    'America/Argentina/La_Rioja': 'Argentina',
    'America/Argentina/Mendoza': 'Argentina',
    'America/Argentina/Rio_Gallegos': 'Argentina',
    'America/Argentina/Salta': 'Argentina',
    'America/Argentina/San_Juan': 'Argentina',
    'America/Argentina/San_Luis': 'Argentina',
    'America/Argentina/Tucuman': 'Argentina',
    'America/Argentina/Ushuaia': 'Argentina',
    'America/Asuncion': 'Paraguay',
    'America/Atikokan': 'Canada',
    'America/Bahia': 'Brazil',
    'America/Bahia_Banderas': 'Mexico',
    'America/Barbados': 'Barbados',
    'America/Belem': 'Brazil',
    'America/Belize': 'Belize',
    'America/Blanc-Sablon': 'Canada',
    'America/Boa_Vista': 'Brazil',
    'America/Bogota': 'Colombia',
    'America/Boise': 'United States',
    'America/Cambridge_Bay': 'Canada',
    'America/Campo_Grande': 'Brazil',
    'America/Cancun': 'Mexico',
    'America/Caracas': 'Venezuela',
    'America/Cayenne': 'France',
    'America/Chicago': 'United States',
    'America/Chihuahua': 'Mexico',
    'America/Costa_Rica': 'Costa Rica',
    'America/Creston': 'Canada',
    'America/Cuiaba': 'Brazil',
    'America/Curacao': 'Netherlands',
    'America/Danmarkshavn': 'Greenland',
    'America/Dawson': 'Canada',
    'America/Dawson_Creek': 'Canada',
    'America/Denver': 'United States',
    'America/Detroit': 'United States',
    'America/Edmonton': 'Canada',
    'America/Eirunepe': 'Brazil',
    'America/El_Salvador': 'El Salvador',
    'America/Fort_Nelson': 'Canada',
    'America/Fortaleza': 'Brazil',
    'America/Glace_Bay': 'Canada',
    'America/Goose_Bay': 'Canada',
    'America/Grand_Turk': 'Turks and Caicos Islands',
    'America/Guatemala': 'Guatemala',
    'America/Guayaquil': 'Ecuador',
    'America/Guyana': 'Guyana',
    'America/Halifax': 'Canada',
    'America/Havana': 'Cuba',
    'America/Hermosillo': 'Mexico',
    'America/Indiana/Indianapolis': 'United States',
    'America/Indiana/Knox': 'United States',
    'America/Indiana/Marengo': 'United States',
    'America/Indiana/Petersburg': 'United States',
    'America/Indiana/Tell_City': 'United States',
    'America/Indiana/Vevay': 'United States',
    'America/Indiana/Vincennes': 'United States',
    'America/Indiana/Winamac': 'United States',
    'America/Inuvik': 'Canada',
    'America/Iqaluit': 'Canada',
    'America/Jamaica': 'Jamaica',
    'America/Juneau': 'United States',
    'America/Kentucky/Louisville': 'United States',
    'America/Kentucky/Monticello': 'United States',
    'America/La_Paz': 'Bolivia',
    'America/Lima': 'Peru',
    'America/Los_Angeles': 'United States',
    'America/Maceio': 'Brazil',
    'America/Managua': 'Nicaragua',
    'America/Manaus': 'Brazil',
    'America/Martinique': 'France',
    'America/Matamoros': 'Mexico',
    'America/Mazatlan': 'Mexico',
    'America/Menominee': 'United States',
    'America/Merida': 'Mexico',
    'America/Metlakatla': 'United States',
    'America/Mexico_City': 'Mexico',
    'America/Miquelon': 'France',
    'America/Moncton': 'Canada',
    'America/Monterrey': 'Mexico',
    'America/Montevideo': 'Uruguay',
    'America/Nassau': 'Bahamas',
    'America/New_York': 'United States',
    'America/Nipigon': 'Canada',
    'America/Nome': 'United States',
    'America/Noronha': 'Brazil',
    'America/North_Dakota/Beulah': 'United States',
    'America/North_Dakota/Center': 'United States',
    'America/North_Dakota/New_Salem': 'United States',
    'America/Nuuk': 'Greenland',
    'America/Ojinaga': 'Mexico',
    'America/Panama': 'Panama',
    'America/Pangnirtung': 'Canada',
    'America/Paramaribo': 'Suriname',
    'America/Phoenix': 'United States',
    'America/Port-au-Prince': 'Haiti',
    'America/Port_of_Spain': 'Trinidad and Tobago',
    'America/Porto_Velho': 'Brazil',
    'America/Puerto_Rico': 'Puerto Rico',
    'America/Punta_Arenas': 'Chile',
    'America/Rainy_River': 'Canada',
    'America/Rankin_Inlet': 'Canada',
    'America/Recife': 'Brazil',
    'America/Regina': 'Canada',
    'America/Resolute': 'Canada',
    'America/Rio_Branco': 'Brazil',
    'America/Santarem': 'Brazil',
    'America/Santiago': 'Chile',
    'America/Santo_Domingo': 'Dominican Republic',
    'America/Sao_Paulo': 'Brazil',
    'America/Scoresbysund': 'Greenland',
    'America/Sitka': 'United States',
    'America/St_Johns': 'Canada',
    'America/Swift_Current': 'Canada',
    'America/Tegucigalpa': 'Honduras',
    'America/Thule': 'Greenland',
    'America/Thunder_Bay': 'Canada',
    'America/Tijuana': 'Mexico',
    'America/Toronto': 'Canada',
    'America/Vancouver': 'Canada',
    'America/Whitehorse': 'Canada',
    'America/Winnipeg': 'Canada',
    'America/Yakutat': 'United States',
    'America/Yellowknife': 'Canada',
    'Antarctica/Casey': 'Australia',
    'Antarctica/Davis': 'Australia',
    'Antarctica/DumontDUrville': 'France',
    'Antarctica/Macquarie': 'Australia',
    'Antarctica/Mawson': 'Australia',
    'Antarctica/Palmer': 'Chile',
    'Antarctica/Rothera': 'Argentina',
    'Antarctica/Syowa': 'Japan',
    'Antarctica/Troll': 'Norway',
    'Antarctica/Vostok': 'Russia',
    'Asia/Almaty': 'Kazakhstan',
    'Asia/Amman': 'Jordan',
    'Asia/Anadyr': 'Russia',
    'Asia/Aqtau': 'Kazakhstan',
    'Asia/Aqtobe': 'Kazakhstan',
    'Asia/Ashgabat': 'Turkmenistan',
    'Asia/Atyrau': 'Kazakhstan',
    'Asia/Baghdad': 'Iraq',
    'Asia/Baku': 'Azerbaijan',
    'Asia/Bangkok': 'Thailand',
    'Asia/Barnaul': 'Russia',
    'Asia/Beirut': 'Lebanon',
    'Asia/Bishkek': 'Kyrgyzstan',
    'Asia/Brunei': 'Brunei',
    'Asia/Chita': 'Russia',
    'Asia/Choibalsan': 'Mongolia',
    'Asia/Colombo': 'Sri Lanka',
    'Asia/Damascus': 'Syria',
    'Asia/Dhaka': 'Bangladesh',
    'Asia/Dili': 'Timor-Leste',
    'Asia/Dubai': 'United Arab Emirates',
    'Asia/Dushanbe': 'Tajikistan',
    'Asia/Famagusta': 'Cyprus',
    'Asia/Gaza': 'Palestine',
    'Asia/Hebron': 'Palestine',
    'Asia/Ho_Chi_Minh': 'Vietnam',
    'Asia/Hong_Kong': 'Hong Kong',
    'Asia/Hovd': 'Mongolia',
    'Asia/Irkutsk': 'Russia',
    'Asia/Jakarta': 'Indonesia',
    'Asia/Jayapura': 'Indonesia',
    'Asia/Jerusalem': 'Israel',
    'Asia/Kabul': 'Afghanistan',
    'Asia/Kamchatka': 'Russia',
    'Asia/Karachi': 'Pakistan',
    'Asia/Kathmandu': 'Nepal',
    'Asia/Khandyga': 'Russia',
    'Asia/Kolkata': 'India',
    'Asia/Krasnoyarsk': 'Russia',
    'Asia/Kuala_Lumpur': 'Malaysia',
    'Asia/Kuching': 'Malaysia',
    'Asia/Macau': 'China',
    'Asia/Magadan': 'Russia',
    'Asia/Makassar': 'Indonesia',
    'Asia/Manila': 'Philippines',
    'Asia/Nicosia': 'Cyprus',
    'Asia/Novokuznetsk': 'Russia',
    'Asia/Novosibirsk': 'Russia',
    'Asia/Omsk': 'Russia',
    'Asia/Oral': 'Kazakhstan',
    'Asia/Phnom_Penh': 'Cambodia',
    'Asia/Pontianak': 'Indonesia',
    'Asia/Pyongyang': 'North Korea',
    'Asia/Qatar': 'Qatar',
    'Asia/Qyzylorda': 'Kazakhstan',
    'Asia/Rangoon': 'Myanmar',
    'Asia/Riyadh': 'Saudi Arabia',
    'Asia/Sakhalin': 'Russia',
    'Asia/Samarkand': 'Uzbekistan',
    'Asia/Seoul': 'South Korea',
    'Asia/Shanghai': 'China',
    'Asia/Singapore': 'Singapore',
    'Asia/Srednekolymsk': 'Russia',
    'Asia/Taipei': 'Taiwan',
    'Asia/Tashkent': 'Uzbekistan',
    'Asia/Tbilisi': 'Georgia',
    'Asia/Tehran': 'Iran',
    'Asia/Thimphu': 'Bhutan',
    'Asia/Tokyo': 'Japan',
    'Asia/Tomsk': 'Russia',
    'Asia/Ulaanbaatar': 'Mongolia',
    'Asia/Urumqi': 'China',
    'Asia/Vientiane': 'Laos',
    'Asia/Vladivostok': 'Russia',
    'Asia/Yakutsk': 'Russia',
    'Asia/Yekaterinburg': 'Russia',
    'Asia/Yerevan': 'Armenia',
    'Atlantic/Azores': 'Portugal',
    'Atlantic/Bermuda': 'Bermuda',
    'Atlantic/Canary': 'Spain',
    'Atlantic/Cape_Verde': 'Cape Verde',
    'Atlantic/Faroe': 'Faroe Islands',
    'Atlantic/Madeira': 'Portugal',
    'Atlantic/Reykjavik': 'Iceland',
    'Atlantic/South_Georgia': 'British Overseas Territory',
    'Atlantic/St_Helena': 'Saint Helena, Ascension and Tristan da Cunha',
    'Atlantic/Stanley': 'Falkland Islands',
    'Australia/Adelaide': 'Australia',
    'Australia/Brisbane': 'Australia',
    'Australia/Broken_Hill': 'Australia',
    'Australia/Currie': 'Australia',
    'Australia/Darwin': 'Australia',
    'Australia/Eucla': 'Australia',
    'Australia/Hobart': 'Australia',
    'Australia/Lindeman': 'Australia',
    'Australia/Lord_Howe': 'Australia',
    'Australia/Melbourne': 'Australia',
    'Australia/Perth': 'Australia',
    'Australia/Sydney': 'Australia',
    'Europe/Amsterdam': 'Netherlands',
    'Europe/Andorra': 'Andorra',
    'Europe/Astrakhan': 'Russia',
    'Europe/Athens': 'Greece',
    'Europe/Belgrade': 'Serbia',
    'Europe/Berlin': 'Germany',
    'Europe/Bratislava': 'Slovakia',
    'Europe/Brussels': 'Belgium',
    'Europe/Bucharest': 'Romania',
    'Europe/Budapest': 'Hungary',
    'Europe/Busingen': 'Germany',
    'Europe/Chisinau': 'Moldova',
    'Europe/Copenhagen': 'Denmark',
    'Europe/Dublin': 'Ireland',
    'Europe/Gibraltar': 'Gibraltar',
    'Europe/Guernsey': 'Bailiwick of Guernsey',
    'Europe/Helsinki': 'Finland',
    'Europe/Isle_of_Man': 'Isle of Man',
    'Europe/Istanbul': 'Turkey',
    'Europe/Jersey': 'Bailiwick of Jersey',
    'Europe/Kaliningrad': 'Russia',
    'Europe/Kiev': 'Ukraine',
    'Europe/Kirov': 'Russia',
    'Europe/Lisbon': 'Portugal',
    'Europe/Ljubljana': 'Slovenia',
    'Europe/London': 'United Kingdom',
    'Europe/Luxembourg': 'Luxembourg',
    'Europe/Madrid': 'Spain',
    'Europe/Malta': 'Malta',
    'Europe/Mariehamn': 'Aland Islands',
    'Europe/Minsk': 'Belarus',
    'Europe/Monaco': 'Monaco',
    'Europe/Moscow': 'Russia',
    'Europe/Oslo': 'Norway',
    'Europe/Paris': 'France',
    'Europe/Podgorica': 'Montenegro',
    'Europe/Prague': 'Czech Republic',
    'Europe/Riga': 'Latvia',
    'Europe/Rome': 'Italy',
    'Europe/Samara': 'Russia',
    'Europe/San_Marino': 'San Marino',
    'Europe/Sarajevo': 'Bosnia and Herzegovina',
    'Europe/Simferopol': 'Russia',
    'Europe/Skopje': 'North Macedonia',
    'Europe/Sofia': 'Bulgaria',
    'Europe/Stockholm': 'Sweden',
    'Europe/Tallinn': 'Estonia',
    'Europe/Tirane': 'Albania',
    'Europe/Ulyanovsk': 'Russia',
    'Europe/Uzhgorod': 'Ukraine',
    'Europe/Vaduz': 'Liechtenstein',
    'Europe/Vatican': 'Vatican City',
    'Europe/Vienna': 'Austria',
    'Europe/Vilnius': 'Lithuania',
    'Europe/Volgograd': 'Russia',
    'Europe/Warsaw': 'Poland',
    'Europe/Zagreb': 'Croatia',
    'Europe/Zaporozhye': 'Ukraine',
    'Europe/Zurich': 'Switzerland',
    'Indian/Antananarivo': 'Madagascar',
    'Indian/Chagos': 'British Indian Ocean Territory',
    'Indian/Christmas': 'Christmas Island',
    'Indian/Cocos': 'Cocos Islands',
    'Indian/Comoro': 'Comoros',
    'Indian/Kerguelen': 'French Southern and Antarctic Lands',
    'Indian/Mahe': 'Seychelles',
    'Indian/Maldives': 'Maldives',
    'Indian/Mauritius': 'Mauritius',
    'Indian/Mayotte': 'Mayotte',
    'Indian/Reunion': 'Reunion',
    'Pacific/Apia': 'Samoa',
    'Pacific/Auckland': 'New Zealand',
    'Pacific/Bougainville': 'Papua New Guinea',
    'Pacific/Chatham': 'New Zealand',
    'Pacific/Chuuk': 'Micronesia',
    'Pacific/Easter': 'Chile',
    'Pacific/Efate': 'Vanuatu',
    'Pacific/Enderbury': 'Kiribati',
    'Pacific/Fakaofo': 'Tokelau',
    'Pacific/Fiji': 'Fiji',
    'Pacific/Funafuti': 'Tuvalu',
    'Pacific/Galapagos': 'Galápagos Islands',
    'Pacific/Gambier': 'French Polynesia',
    'Pacific/Guadalcanal': 'Solomon Islands',
    'Pacific/Guam': 'Guam',
    'Pacific/Honolulu': 'United States',
    'Pacific/Johnston': 'United States',
    'Pacific/Kiritimati': 'Christmas Island',
    'Pacific/Kosrae': 'Micronesia',
    'Pacific/Kwajalein': 'Marshall Islands',
    'Pacific/Majuro': 'Marshall Islands',
    'Pacific/Marquesas': 'French Polynesia',
    'Pacific/Midway': 'United States',
    'Pacific/Nauru': 'Nauru',
    'Pacific/Niue': 'Niue',
    'Pacific/Norfolk': 'Norfolk Island',
    'Pacific/Noumea': 'New Caledonia',
    'Pacific/Pago_Pago': 'American Samoa',
    'Pacific/Palau': 'Palau',
    'Pacific/Pitcairn': 'Pitcairn Islands',
    'Pacific/Pohnpei': 'Micronesia',
    'Pacific/Port_Moresby': 'Papua New Guinea',
    'Pacific/Rarotonga': 'Cook Islands',
    'Pacific/Saipan': 'Northern Mariana Islands',
    'Pacific/Tahiti': 'French Polynesia',
    'Pacific/Tarawa': 'Kiribati',
    'Pacific/Tongatapu': 'Tonga',
    'Pacific/Wake': 'United States',
    'Pacific/Wallis': 'Wallis and Futuna'
}
countries = {
    'British Overseas Territory': '',
    'Galápagos Islands': '',
    'French Polynesia': 'PF',
    'Guam': 'GU',
    'Niue': 'NU',
    'Norfolk Island': 'NF',
    'New Caledonia': 'NC',
    'Isle of Man': 'IM',
    'American Samoa': 'AS',
    'Pitcairn Islands': 'PN',
    'Cook Islands': 'CK',
    'Northern Mariana Islands': 'MP',
    'Wallis and Futuna': 'WF',
    'Afghanistan': 'AF',
    'Albania': 'AL',
    'Algeria': 'DZ',
    'Aland Islands': 'AX',
    'Andorra': 'AD',
    'Angola': 'AO',
    'Antigua and Barbuda': 'AG',
    'Argentina': 'AR',
    'Armenia': 'AM',
    'Australia': 'AU',
    'Austria': 'AT',
    'Azerbaijan': 'AZ',
    'Bahamas': 'BS',
    'Bahrain': 'BH',
    'Bailiwick of Guernsey': 'GG',
    'Bailiwick of Jersey': 'JE',
    'Bangladesh': 'BD',
    'Barbados': 'BB',
    'Belarus': 'BY',
    'Belgium': 'BE',
    'Belize': 'BZ',
    'Benin': 'BJ',
    'Bermuda': 'BM',
    'Bhutan': 'BT',
    'Bolivia': 'BO',
    'Bosnia and Herzegovina': 'BA',
    'Botswana': 'BW',
    'Brazil': 'BR',
    'British Indian Ocean Territory': 'IO',
    'Brunei': 'BN',
    'Bulgaria': 'BG',
    'Burkina Faso': 'BF',
    'Burma': 'MM',
    'Burundi': 'BI',
    'Cambodia': 'KH',
    'Cameroon': 'CM',
    'Canada': 'CA',
    'Cape Verde': 'CV',
    'Central African Republic': 'CF',
    'Chad': 'TD',
    'Chile': 'CL',
    'China': 'CN',
    'Christmas Island': 'CX',
    'Cocos Islands': 'CC',
    'Colombia': 'CO',
    'Comoros': 'KM',
    'Congo, Democratic Republic of the': 'CD',
    'Congo, Republic of the': 'CG',
    'Costa Rica': 'CR',
    'Ivory Coast': 'CI',
    'Croatia': 'HR',
    'Cuba': 'CU',
    'Cyprus': 'CY',
    'Czech Republic': 'CZ',
    'Denmark': 'DK',
    'Djibouti': 'DJ',
    'Dominica': 'DM',
    'Dominican Republic': 'DO',
    'Timor-Leste': 'TL',
    'Ecuador': 'EC',
    'Egypt': 'EG',
    'El Salvador': 'SV',
    'Equatorial Guinea': 'GQ',
    'Eritrea': 'ER',
    'Estonia': 'EE',
    'Ethiopia': 'ET',
    'Falkland Islands': 'FK',
    'Faroe Islands': 'FO',
    'Fiji': 'FJ',
    'Finland': 'FI',
    'France': 'FR',
    'French Southern and Antarctic Lands': 'TF',
    'Gabon': 'GA',
    'Gambia': 'GM',
    'Georgia': 'GE',
    'Germany': 'DE',
    'Ghana': 'GH',
    'Gibraltar': 'GI',
    'Greece': 'GR',
    'Greenland': 'GL',
    'Grenada': 'GD',
    'Guatemala': 'GT',
    'Guinea': 'GN',
    'Guinea-Bissau': 'GW',
    'Guyana': 'GY',
    'Haiti': 'HT',
    'Honduras': 'HN',
    'Hungary': 'HU',
    'Iceland': 'IS',
    'India': 'IN',
    'Indonesia': 'ID',
    'Iran': 'IR',
    'Iraq': 'IQ',
    'Ireland': 'IE',
    'Israel': 'IL',
    'Italy': 'IT',
    'Jamaica': 'JM',
    'Japan': 'JP',
    'Jordan': 'JO',
    'Kazakhstan': 'KZ',
    'Kenya': 'KE',
    'Kiribati': 'KI',
    'North Korea': 'KP',
    'South Korea': 'KR',
    'Kuwait': 'KW',
    'Kyrgyzstan': 'KG',
    'Laos': 'LA',
    'Latvia': 'LV',
    'Lebanon': 'LB',
    'Lesotho': 'LS',
    'Liberia': 'LR',
    'Libya': 'LY',
    'Liechtenstein': 'LI',
    'Lithuania': 'LT',
    'Luxembourg': 'LU',
    'Macedonia': 'MK',
    'Madagascar': 'MG',
    'Malawi': 'MW',
    'Malaysia': 'MY',
    'Maldives': 'MV',
    'Mali': 'ML',
    'Malta': 'MT',
    'Marshall Islands': 'MH',
    'Mauritania': 'MR',
    'Mauritius': 'MU',
    'Mayotte': 'YT',
    'Mexico': 'MX',
    'Micronesia': 'FM',
    'Moldova': 'MD',
    'Monaco': 'MC',
    'Mongolia': 'MN',
    'Montenegro': 'ME',
    'Morocco': 'MA',
    'Mozambique': 'MZ',
    'Myanmar': 'MM',
    'Namibia': 'NA',
    'Nauru': 'NR',
    'Nepal': 'NP',
    'Netherlands': 'NL',
    'New Zealand': 'NZ',
    'Nicaragua': 'NI',
    'Niger': 'NE',
    'Nigeria': 'NG',
    'North Macedonia': 'MK',
    'Norway': 'NO',
    'Oman': 'OM',
    'Pakistan': 'PK',
    'Palau': 'PW',
    'Palestine': 'PS',
    'Panama': 'PA',
    'Papua New Guinea': 'PG',
    'Paraguay': 'PY',
    'Peru': 'PE',
    'Philippines': 'PH',
    'Poland': 'PL',
    'Portugal': 'PT',
    'Puerto Rico': 'PR',
    'Qatar': 'QA',
    'Reunion': 'RE',
    'Romania': 'RO',
    'Russia': 'RU',
    'Rwanda': 'RW',
    'Saint Helena, Ascension and Tristan da Cunha': 'SH',
    'Saint Kitts and Nevis': 'KN',
    'Saint Lucia': 'LC',
    'Saint Vincent and the Grenadines': 'VC',
    'Samoa': 'WS',
    'San Marino': 'SM',
    'Sao Tome and Principe': 'ST',
    'Saudi Arabia': 'SA',
    'Senegal': 'SN',
    'Serbia': 'RS',
    'Seychelles': 'SC',
    'Sierra Leone': 'SL',
    'Singapore': 'SG',
    'Slovakia': 'SK',
    'Slovenia': 'SI',
    'Solomon Islands': 'SB',
    'Somalia': 'SO',
    'South Africa': 'ZA',
    'South Sudan': 'SS',
    'Spain': 'ES',
    'Sri Lanka': 'LK',
    'Sudan': 'SD',
    'Suriname': 'SR',
    'Swaziland': 'SZ',
    'Sweden': 'SE',
    'Switzerland': 'CH',
    'Syria': 'SY',
    'Taiwan': 'TW',
    'Tajikistan': 'TJ',
    'Tanzania': 'TZ',
    'Thailand': 'TH',
    'Togo': 'TG',
    'Tokelau': 'TK',
    'Tonga': 'TO',
    'Trinidad and Tobago': 'TT',
    'Tunisia': 'TN',
    'Turkey': 'TR',
    'Turkmenistan': 'TM',
    'Turks and Caicos Islands': 'TC',
    'Tuvalu': 'TV',
    'Uganda': 'UG',
    'Ukraine': 'UA',
    'United Arab Emirates': 'AE',
    'United Kingdom': 'GB',
    'United States': 'US',
    'Uruguay': 'UY',
    'Uzbekistan': 'UZ',
    'Vanuatu': 'VU',
    'Vatican City': 'VA',
    'Venezuela': 'VE',
    'Vietnam': 'VN',
    'Western Sahara': 'EH',
    'Yemen': 'YE',
    'Zambia': 'ZM',
    'Zimbabwe': 'ZW',
    'Hong Kong': 'HK',
}

timezone_to_country = dict(
    sorted(timezone_to_country.items(), key=lambda item: item[1]))

for k, v in timezone_to_country.items():
    tmp = k.split('/')[-1].replace("_", " ")
    # get http request from worldtimeapi.org
    # keep trying until we get a response
    while True:
        try:
            response = requests.get(
                f"http://worldtimeapi.org/api/timezone/{k}")
            break
        except:
            pass
    # get utc offset from response
    try:
        offset = response.json()['utc_offset']
    except:
        continue
    print(
        f"WorldTime(location: \"{tmp}, {v}\", flag: \"{countries[v]}\", utc: \"{offset}\"),")
